Add logic to write method of out_opensearch_data_stream
fluent/fluent-plugin-opensearch pull request #109
Opened 2023-07-11 04:28 UTC by renegaderyu

- Add tag_key to record and remove keys if config options are set.
- Fix issue #83.
- Fix typo/language in README related to contributions.

Details
I've added test cases; however, when I try to run them locally I get the error included below. This happens for all test that include datastreams
`Fluent::ConfigError:` Failed to create data stream: <foo> unknown keyword: acknowledged`

(check all that apply)
- [X] tests added
- [ ? ] tests passing
- [X] README updated (if needed)
- [X] README Table of Contents updated (if needed)
- [X] History.md and `version` in gemspec are untouched
- [X] backward compatible

2023-07-24 17:20 UTC, renegaderyu commented
@cosmo0920 can you please look at this PR and advise?

2023-08-10 00:55 UTC, renegaderyu commented
@cosmo0920 or @ashie can you please look at this PR and advise? I'm hoping that the next plugin version can keep the tag field on the records and use the remove_keys option.

2023-08-10 01:29 UTC, daipom commented
Sorry for the late response.
Thanks for your contribution!
I will see this this week.

Could you add DCO to your commit message?

2023-08-10 08:54 UTC, cosmo0920 requested changes
This patch itself would be great. However, we need to follow DCO process.
Could you sign your commits by following the DCO process?
https://github.com/fluent/fluent-plugin-opensearch/pull/109/checks?check_run_id=14933247397

2023-08-11 01:55 UTC, cosmo0920 reviewed
I kicked the CI tasks. Waiting for the results.

2023-08-11 13:49 UTC, cosmo0920 commented
test_record_with_include_tag_key(OpenSearchOutputDataStreamTest) is failing. Could you get rid of this failure?

2023-08-11 13:50 UTC, cosmo0920 commented
The other part looks attractive. :smile:

2023-08-14 16:58 UTC, renegaderyu commented
> I kicked the CI tasks. Waiting for the results.
> test_record_with_include_tag_key(OpenSearchOutputDataStreamTest) is failing. Could you get rid of this failure?
> The other part looks attractive. 😄

Thanks, I think I've fixed the logic that was causing failure but I can't seem to test locally.

2023-08-17 08:53 UTC, cosmo0920 commented
Do you all have a cycle to take a look on this? @ashie @daipom ?

2023-08-17 10:48 UTC, daipom commented
I'm sorry for my late response.

I think this change of `flexmock` is the trigger.

https://github.com/doudou/flexmock/commit/f48461b8666e8009352d0553dd3615aa1c18facc#diff-ceb1ae5adf57a3b493bef8b8fcf50ec0d484e4ce960aeda3f3076dc480429309R33-R34

Since this plugin loads `minitest`, this logic wrongly judges that the test framework is MiniTest I think.

https://github.com/fluent/fluent-plugin-opensearch/blob/e351ee8910a3416c8899284d5e7f8c3cd45c9ac4/test/helper.rb#L58

We should remove this `require`.

2023-08-17 11:16 UTC, cosmo0920 commented
@renegaderyu CI errors was fixed by @danpom. So, could you rebase off master, please?

2023-08-18 01:40 UTC, cosmo0920 approved these changes

2023-08-18 01:41 UTC, merged

2023-08-18 02:33 UTC, daipom commented
Thanks @renegaderyu @cosmo0920 !