pin dependency opensearch-ruby t0 3.0.1
fluent/fluent-plugin-opensearch pull request #116
Opened 2023-09-20 06:39 UTC by 24367dfa

DESCRIPTION HERE

(check all that apply)
- [ ] tests added
- [ ] tests passing
- [ ] README updated (if needed)
- [ ] README Table of Contents updated (if needed)
- [ ] History.md and `version` in gemspec are untouched
- [ ] backward compatible

2023-09-22 06:05 UTC, 24367dfa commented
@cosmo0920 can i do anything else to move this PR forward?

2023-09-25 03:44 UTC, cosmo0920 commented
Almost all of tests are failed. We can't proceed this PR as-is. Would you mind if you tried to fix the failures? Or, do you need help for your fixes with @kenhys or @ashie?

2023-09-25 06:05 UTC, 24367dfa commented
> Almost all of tests are failed. We can't proceed this PR as-is. Would you mind if you tried to fix the failures? Or, do you need help for your fixes with @kenhys or @ashie?

i'll try my best fo fix this and will report back the day after tomorrow.

2023-09-25 19:30 UTC, 24367dfa commented
> > Almost all of tests are failed. We can't proceed this PR as-is. Would you mind if you tried to fix the failures? Or, do you need help for your fixes with @kenhys or @ashie?
> 
> i'll try my best fo fix this and will report back the day after tomorrow.

I have difficulties to get the test setup running. I installed ruby 3.2.2 using rbenv and can locally reproduce the failing test run on ubuntu. (yay)

To get to a working state to start working off of, i tried running the tests for `v1.1.4` (the last successful run of github actions) but i am seeing the same `can't modify frozen String: ""` errors as in the CI runs of this PR.

Am i holding it wrong?

Steps to reproduce:

```
curl -sL https://github.com/rbenv/rbenv-installer/raw/main/bin/rbenv-installer | bash -
rbenv install 3.2.2
rbenv global 3.2.2
git clone git@github.com:24367dfa/fluent-plugin-opensearch.git
cd fluent-plugin-opensearch
gem install bundler rake
bundle install
bundle exec rake test
```

2023-09-29 20:42 UTC, 24367dfa commented
@cosmo0920 pinning webmock to 3.18.1 gets rid of the errors. could you approve another CI run?

2023-10-02 03:54 UTC, cosmo0920 requested changes

2023-10-02 03:54 UTC, cosmo0920 commented on fluent-plugin-opensearch.gemspec
> +  s.add_development_dependency 'webmock', '= 3.18.1'
How about pinning webmock version with `~> 3.18.1`. Precisely version locking is sick for us.

2023-10-02 05:55 UTC, cosmo0920 commented
> @cosmo0920 pinning webmock to 3.18.1 gets rid of the errors. could you approve another CI run?

Could you follow DCO process again? DCO is failed now.

2023-10-03 07:31 UTC, 24367dfa commented
> > @cosmo0920 pinning webmock to 3.18.1 gets rid of the errors. could you approve another CI run?
> 
> Could you follow DCO process again? DCO is failed now.

/done :)

2023-10-03 07:42 UTC, cosmo0920 approved these changes

2023-10-03 08:18 UTC, merged

2023-10-03 08:19 UTC, cosmo0920 commented
Did you all have cycles to release this PR as v1.2.0, @kenhys @ashie?