Added a retry logic for both client creation and search operations in case of connection failures.
fluent/fluent-plugin-opensearch pull request #136
Opened 2024-04-14 11:19 UTC by OlehPalanskyi

### Description

**Problem**: 
If there are two servers in the hosts field (example: hosts "server1:9200,server2:9200"), automatic switching to the available host does not work. If server1 is unavailable, it does not switch to server2, and the service writes an error and freezes:
"Unexpected error raised. Stopping the timer. title=:in_opensearch_timer error_class=Faraday::ConnectionFailed error="EOFError (EOFError)""

**Solution**:
I added a retry logic for both client creation and search operations in case of connection failures. 
And added ignoring any clear_scroll errors.

Signed-off-by: Oleh Palanskyi <trahterber@gmail.com>
<img width="1192" alt="Monosnap Dockerfile—2024-04-14 14-18-21" src="https://github.com/fluent/fluent-plugin-opensearch/assets/39740197/e2de88f3-721b-43ac-835b-d91cd2a5eb65">

2024-04-15 09:19 UTC, cosmo0920 requested changes
I left some of the my concerns. No worries, the direction of the patch should be reasonable but we need to handle for error cases and retrying period precisely.

2024-04-15 09:19 UTC, cosmo0920 commented on lib/fluent/plugin/in_opensearch.rb
> +            if @infinite_check_connection == true
```suggestion
            if @infinite_check_connection
```

`== true` is redundant because if clause already handles boolean value.

2024-04-15 09:19 UTC, cosmo0920 commented on lib/fluent/plugin/in_opensearch.rb
> +              )
Creating a method that is only used for verifying reachable hosts would be better instead of just writing down whole things to do so.

2024-04-15 09:19 UTC, cosmo0920 commented on lib/fluent/plugin/in_opensearch.rb
> +        sleep(@request_timeout)
Just waiting for periodically is reasonable for this case? In Fluentd, we have [retry_state](https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin_helper/retry_state.rb) plugin helper to create/manage retrying statuses. Could you use it if you have a capability for it?

2024-04-15 09:19 UTC, cosmo0920 commented on lib/fluent/plugin/in_opensearch.rb
> +      retry
Infinite retrying without any conditions are sick for us. We should provide some of the choices whether this feature should be enabled or not. What you you think?

2024-04-15 09:34 UTC, OlehPalanskyi commented
Thank you for your comments
I'll rework my patch based on your suggestions.

2024-04-25 02:25 UTC, cosmo0920 requested changes

2024-04-25 02:25 UTC, cosmo0920 commented on lib/fluent/plugin/in_opensearch.rb
> +      @retry.instance_variable_set(:@next_time, nil)
Basically, your patch is almost overwhelmed my expectations! Quite good work.
One thing, retry_state instance should be reinitialized like as plugin/output.rb does in Fluentd core:
https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/output.rb#L1119
https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/output.rb#L1314-L1315

So, eliminate the contents of `@retry` here with: `@retry = nil`
And, recreating in https://github.com/fluent/fluent-plugin-opensearch/pull/136/files#diff-61847321aa21e1cfdbc79e273831965c71d90b38ed24e8fe480bf5bcc908e0e4R351 with

```ruby
unless @retry
   @retry = retry_state(@retry_randomize)
end
```
would be needed. Other places are perfectly implemented. :+1:

2024-04-26 04:03 UTC, cosmo0920 approved these changes
Thanks for your work. It's brilliant work! All of the implementation should be exceeded my expectations.

2024-04-26 04:03 UTC, cosmo0920 commented
@kenhys Any concerns?

2024-04-26 04:06 UTC, cosmo0920 commented
On thing, I had a nitpick though. The retry_state should be used inside of `<buffer>` sections. However, Input plugins of Fluentd do not have buffering mechanism. So, it should be wrong usage if we use `<buffer>` for this retrying functionality.
How you do think this nitpick, @kenhys or @daipom ?

2024-04-30 04:10 UTC, merged