Use template_file for Data Streams
fluent/fluent-plugin-opensearch pull request #20
Opened 2022-02-14 14:55 UTC by anders-swanson

Signed-off-by: Anders Swanson <anders.swanson@oracle.com>

Currently template_file parameter is not supported by datastream output. This would add creation of index template, it was not working before.

(check all that apply)
- [x] tests added
- [x] tests passing
- [ ] README updated (if needed)
- [ ] README Table of Contents updated (if needed)
- [x] History.md and `version` in gemspec are untouched
- [x] backward compatible

2022-02-15 05:00 UTC, cosmo0920 requested changes
Your implementation is good. But, I found an issue for stability on unstable working connections.

2022-02-15 13:59 UTC, anders-swanson commented on lib/fluent/plugin/out_opensearch_data_stream.rb
> +        template_installation_actual(template_name, @customize_template, @application_name, datastream_name, host)
Isn't this redundant with the implementation of `template_installation_actual`? This function already uses `retry_operate` internally: https://github.com/fluent/fluent-plugin-opensearch/blob/main/lib/fluent/plugin/out_opensearch.rb#L1038

2022-02-16 00:10 UTC, cosmo0920 commented on lib/fluent/plugin/out_opensearch_data_stream.rb
> +        template_installation_actual(template_name, @customize_template, @application_name, datastream_name, host)
Ah, I'd overlooked this. Yeah, your implementation is correct.

2022-02-16 02:32 UTC, cosmo0920 approved these changes
:+1:

2022-02-16 02:32 UTC, merged